<?php
global $countries, $states;

$countries = array(
    'Anywhere' => __('Anywhere', 'appthemes'), 
    'AF' => __('Afganistan', 'appthemes'), 
    'AL' => __('Albania', 'appthemes'), 
    'DZ' => __('Algeria', 'appthemes'), 
    'AS' => __('American Samoa', 'appthemes'), 
    'AD' => __('Andorra', 'appthemes'),  
    'AO' => __('Angola', 'appthemes'), 
    'AI' => __('Anguilla', 'appthemes'), 
    'AQ' => __('Antarctica', 'appthemes'), 
    'AG' => __('Antigua and Barbuda', 'appthemes'),  
    'AR' => __('Argentina', 'appthemes'),  
    'AM' => __('Armenia', 'appthemes'),  
    'AW' => __('Aruba', 'appthemes'),  
    'AU' => __('Australia', 'appthemes'),  
    'AT' => __('Austria', 'appthemes'),  
    'AZ' => __('Azerbaijan', 'appthemes'), 
    'BS' => __('Bahamas', 'appthemes'),  
    'BH' => __('Bahrain', 'appthemes'),  
    'BD' => __('Bangladesh', 'appthemes'), 
    'BB' => __('Barbados', 'appthemes'), 
    'BY' => __('Belarus', 'appthemes'),  
    'BE' => __('Belgium', 'appthemes'),  
    'BZ' => __('Belize', 'appthemes'), 
    'BJ' => __('Benin', 'appthemes'),  
    'BM' => __('Bermuda', 'appthemes'),  
    'BT' => __('Bhutan', 'appthemes'), 
    'BO' => __('Bolivia', 'appthemes'),  
    'BA' => __('Bosnia and Herzegowina', 'appthemes'), 
    'BW' => __('Botswana', 'appthemes'), 
    'BV' => __('Bouvet Island', 'appthemes'),  
    'BR' => __('Brazil', 'appthemes'), 
    'IO' => __('British Indian Ocean Territory', 'appthemes'), 
    'BN' => __('Brunei Darussalam', 'appthemes'),  
    'BG' => __('Bulgaria', 'appthemes'), 
    'BF' => __('Burkina Faso', 'appthemes'), 
    'BI' => __('Burundi', 'appthemes'),  
    'KH' => __('Cambodia', 'appthemes'), 
    'CM' => __('Cameroon', 'appthemes'), 
    'CA' => __('Canada', 'appthemes'), 
    'CV' => __('Cape Verde', 'appthemes'), 
    'KY' => __('Cayman Islands', 'appthemes'), 
    'CF' => __('Central African Republic', 'appthemes'), 
    'TD' => __('Chad', 'appthemes'), 
    'CL' => __('Chile', 'appthemes'),  
    'CN' => __('China', 'appthemes'), 
    'CX' => __('Christmas Island', 'appthemes'),     
    'CC' => __('Cocos (Keeling) Islands', 'appthemes'),  
    'CO' => __('Colombia', 'appthemes'), 
    'KM' => __('Comoros', 'appthemes'),  
    'CG' => __('Congo', 'appthemes'),  
    'CD' => __('Congo, the Democratic Republic of the', 'appthemes'),  
    'CK' => __('Cook Islands', 'appthemes'), 
    'CR' => __('Costa Rica', 'appthemes'), 
    'CI' => __('Cote d\'Ivoire', 'appthemes'),  
    'HR' => __('Croatia (Hrvatska)', 'appthemes'), 
    'CU' => __('Cuba', 'appthemes'), 
    'CY' => __('Cyprus', 'appthemes'), 
    'CZ' => __('Czech Republic', 'appthemes'), 
    'DK' => __('Denmark', 'appthemes'),  
    'DJ' => __('Djibouti', 'appthemes'), 
    'DM' => __('Dominica', 'appthemes'), 
    'DO' => __('Dominican Republic', 'appthemes'), 
    'TP' => __('East Timor', 'appthemes'), 
    'EC' => __('Ecuador', 'appthemes'),  
    'EG' => __('Egypt', 'appthemes'),  
    'SV' => __('El Salvador', 'appthemes'),  
    'GQ' => __('Equatorial Guinea', 'appthemes'),  
    'ER' => __('Eritrea', 'appthemes'),  
    'EE' => __('Estonia', 'appthemes'),  
    'ET' => __('Ethiopia', 'appthemes'), 
    'FK' => __('Falkland Islands (Malvinas)', 'appthemes'),  
    'FO' => __('Faroe Islands', 'appthemes'),  
    'FJ' => __('Fiji', 'appthemes'), 
    'FI' => __('Finland', 'appthemes'), 
    'FR' => __('France', 'appthemes'), 
    'FX' => __('France, Metropolitan', 'appthemes'), 
    'GF' => __('French Guiana', 'appthemes'),  
    'PF' => __('French Polynesia', 'appthemes'), 
    'TF' => __('French Southern Territories', 'appthemes'),  
    'GA' => __('Gabon', 'appthemes'),  
    'GM' => __('Gambia', 'appthemes'), 
    'GE' => __('Georgia', 'appthemes'),  
    'DE' => __('Germany', 'appthemes'),  
    'GH' => __('Ghana', 'appthemes'),  
    'GI' => __('Gibraltar', 'appthemes'),  
    'GR' => __('Greece', 'appthemes'), 
    'GL' => __('Greenland', 'appthemes'),  
    'GD' => __('Grenada', 'appthemes'),  
    'GP' => __('Guadeloupe', 'appthemes'), 
    'GU' => __('Guam', 'appthemes'), 
    'GT' => __('Guatemala', 'appthemes'),  
    'GN' => __('Guinea', 'appthemes'), 
    'GW' => __('Guinea-Bissau', 'appthemes'),  
    'GY' => __('Guyana', 'appthemes'), 
    'HT' => __('Haiti', 'appthemes'),  
    'HM' => __('Heard and Mc Donald Islands', 'appthemes'),  
    'VA' => __('Holy See (Vatican City State)', 'appthemes'),  
    'HN' => __('Honduras', 'appthemes'), 
    'HK' => __('Hong Kong', 'appthemes'),  
    'HU' => __('Hungary', 'appthemes'),  
    'IS' => __('Iceland', 'appthemes'),  
    'IN' => __('India', 'appthemes'),  
    'ID' => __('Indonesia', 'appthemes'),  
    'IR' => __('Iran (Islamic Republic of)', 'appthemes'), 
    'IQ' => __('Iraq', 'appthemes'), 
    'IE' => __('Ireland', 'appthemes'),  
    'IL' => __('Israel', 'appthemes'), 
    'IT' => __('Italy', 'appthemes'),  
    'JM' => __('Jamaica', 'appthemes'),  
    'JP' => __('Japan', 'appthemes'), 
    'JO' => __('Jordan', 'appthemes'), 
    'KZ' => __('Kazakhstan', 'appthemes'), 
    'KE' => __('Kenya', 'appthemes'),  
    'KI' => __('Kiribati', 'appthemes'), 
    'KP' => __('Korea, Democratic People\'s Republic of', 'appthemes'), 
    'KR' => __('Korea, Republic of', 'appthemes'), 
    'KW' => __('Kuwait', 'appthemes'), 
    'KG' => __('Kyrgyzstan', 'appthemes'), 
    'LA' => __('Lao People\'s Democratic Republic', 'appthemes'), 
    'LV' => __('Latvia', 'appthemes'), 
    'LB' => __('Lebanon', 'appthemes'), 
    'LS' => __('Lesotho', 'appthemes'),  
    'LR' => __('Liberia', 'appthemes'),  
    'LY' => __('Libyan Arab Jamahiriya', 'appthemes'), 
    'LI' => __('Liechtenstein', 'appthemes'),  
    'LT' => __('Lithuania', 'appthemes'), 
    'LU' => __('Luxembourg', 'appthemes'), 
    'MO' => __('Macau', 'appthemes'),  
    'MK' => __('Macedonia, The Former Yugoslav Republic of', 'appthemes'), 
    'MG' => __('Madagascar', 'appthemes'), 
    'MW' => __('Malawi', 'appthemes'), 
    'MY' => __('Malaysia', 'appthemes'), 
    'MV' => __('Maldives', 'appthemes'), 
    'ML' => __('Mali', 'appthemes'), 
    'MT' => __('Malta', 'appthemes'), 
    'MH' => __('Marshall Islands', 'appthemes'), 
    'MQ' => __('Martinique', 'appthemes'), 
    'MR' => __('Mauritania', 'appthemes'), 
    'MU' => __('Mauritius', 'appthemes'), 
    'YT' => __('Mayotte', 'appthemes'),  
    'MX' => __('Mexico', 'appthemes'), 
    'FM' => __('Micronesia, Federated States of', 'appthemes'), 
    'MD' => __('Moldova, Republic of', 'appthemes'), 
    'MC' => __('Monaco', 'appthemes'), 
    'MN' => __('Mongolia', 'appthemes'), 
    'MS' => __('Montserrat', 'appthemes'), 
    'MA' => __('Morocco', 'appthemes'), 
    'MZ' => __('Mozambique', 'appthemes'), 
    'MM' => __('Myanmar', 'appthemes'), 
    'NA' => __('Namibia', 'appthemes'), 
    'NR' => __('Nauru', 'appthemes'),  
    'NP' => __('Nepal', 'appthemes'),  
    'NL' => __('Netherlands', 'appthemes'), 
    'AN' => __('Netherlands Antilles', 'appthemes'), 
    'NC' => __('New Caledonia', 'appthemes'), 
    'NZ' => __('New Zealand', 'appthemes'),  
    'NI' => __('Nicaragua', 'appthemes'),  
    'NE' => __('Niger', 'appthemes'),  
    'NG' => __('Nigeria', 'appthemes'),  
    'NU' => __('Niue', 'appthemes'), 
    'NF' => __('Norfolk Island', 'appthemes'), 
    'MP' => __('Northern Mariana Islands', 'appthemes'), 
    'NO' => __('Norway', 'appthemes'), 
    'OM' => __('Oman', 'appthemes'), 
    'PK' => __('Pakistan', 'appthemes'), 
    'PW' => __('Palau', 'appthemes'), 
    'PA' => __('Panama', 'appthemes'), 
    'PG' => __('Papua New Guinea', 'appthemes'), 
    'PY' => __('Paraguay', 'appthemes'), 
    'PE' => __('Peru', 'appthemes'), 
    'PH' => __('Philippines', 'appthemes'), 
    'PN' => __('Pitcairn', 'appthemes'), 
    'PL' => __('Poland', 'appthemes'), 
    'PT' => __('Portugal', 'appthemes'), 
    'PR' => __('Puerto Rico', 'appthemes'), 
    'QA' => __('Qatar', 'appthemes'), 
    'RE' => __('Reunion', 'appthemes'), 
    'RO' => __('Romania', 'appthemes'), 
    'RU' => __('Russian Federation', 'appthemes'), 
    'RW' => __('Rwanda', 'appthemes'), 
    'KN' => __('Saint Kitts and Nevis', 'appthemes'),  
    'LC' => __('Saint LUCIA', 'appthemes'),  
    'VC' => __('Saint Vincent and the Grenadines', 'appthemes'), 
    'WS' => __('Samoa', 'appthemes'),  
    'SM' => __('San Marino', 'appthemes'), 
    'ST' => __('Sao Tome and Principe', 'appthemes'), 
    'SA' => __('Saudi Arabia', 'appthemes'), 
    'SN' => __('Senegal', 'appthemes'), 
    'SC' => __('Seychelles', 'appthemes'), 
    'SL' => __('Sierra Leone', 'appthemes'), 
    'SG' => __('Singapore', 'appthemes'),  
    'SK' => __('Slovakia (Slovak Republic)', 'appthemes'), 
    'SI' => __('Slovenia', 'appthemes'), 
    'SB' => __('Solomon Islands', 'appthemes'), 
    'SO' => __('Somalia', 'appthemes'),  
    'ZA' => __('South Africa', 'appthemes'), 
    'GS' => __('South Georgia and the South Sandwich Islands', 'appthemes'), 
    'ES' => __('Spain', 'appthemes'), 
    'LK' => __('Sri Lanka', 'appthemes'), 
    'SH' => __('St. Helena', 'appthemes'), 
    'PM' => __('St. Pierre and Miquelon', 'appthemes'),  
    'SD' => __('Sudan', 'appthemes'),  
    'SR' => __('Suriname', 'appthemes'), 
    'SJ' => __('Svalbard and Jan Mayen Islands', 'appthemes'), 
    'SZ' => __('Swaziland', 'appthemes'),  
    'SE' => __('Sweden', 'appthemes'), 
    'CH' => __('Switzerland', 'appthemes'),  
    'SY' => __('Syrian Arab Republic', 'appthemes'), 
    'TW' => __('Taiwan, Province of China', 'appthemes'), 
    'TJ' => __('Tajikistan', 'appthemes'), 
    'TZ' => __('Tanzania, United Republic of', 'appthemes'), 
    'TH' => __('Thailand', 'appthemes'), 
    'TG' => __('Togo', 'appthemes'), 
    'TK' => __('Tokelau', 'appthemes'), 
    'TO' => __('Tonga', 'appthemes'),  
    'TT' => __('Trinidad and Tobago', 'appthemes'),  
    'TN' => __('Tunisia', 'appthemes'),  
    'TR' => __('Turkey', 'appthemes'), 
    'TM' => __('Turkmenistan', 'appthemes'), 
    'TC' => __('Turks and Caicos Islands', 'appthemes'), 
    'TV' => __('Tuvalu', 'appthemes'), 
    'UG' => __('Uganda', 'appthemes'), 
    'UA' => __('Ukraine', 'appthemes'), 
    'AE' => __('United Arab Emirates', 'appthemes'), 
    'GB' => __('United Kingdom', 'appthemes'), 
    'US' => __('United States', 'appthemes'), 
    'UM' => __('United States Minor Outlying Islands', 'appthemes'), 
    'UY' => __('Uruguay', 'appthemes'),  
    'UZ' => __('Uzbekistan', 'appthemes'), 
    'VU' => __('Vanuatu', 'appthemes'),  
    'VE' => __('Venezuela', 'appthemes'), 
    'VN' => __('Viet Nam', 'appthemes'), 
    'VG' => __('Virgin Islands (British)', 'appthemes'), 
    'VI' => __('Virgin Islands (U.S.)', 'appthemes'),  
    'WF' => __('Wallis and Futuna Islands', 'appthemes'),  
    'EH' => __('Western Sahara', 'appthemes'), 
    'YE' => __('Yemen', 'appthemes'),  
    'YU' => __('Yugoslavia', 'appthemes'), 
    'ZM' => __('Zambia', 'appthemes'), 
    'ZW' => __('Zimbabwe', 'appthemes')             
); 

$states = array(
	'"Alabama"',  
	'"Alaska"',  
	'"Arizona"',  
	'"Arkansas"',  
	'"California"',  
	'"Colorado"',  
	'"Connecticut"',  
	'"Delaware"',  
	'"District Of Columbia"',  
	'"Florida"',  
	'"Georgia"',  
	'"Hawaii"',  
	'"Idaho"',  
	'"Illinois"',  
	'"Indiana"',  
	'"Iowa"',  
	'"Kansas"',  
	'"Kentucky"',  
	'"Louisiana"',  
	'"Maine"',  
	'"Maryland"',  
	'"Massachusetts"',  
	'"Michigan"',  
	'"Minnesota"',  
	'"Mississippi"',  
	'"Missouri"',  
	'"Montana"', 
	'"Nebraska"', 
	'"Nevada"', 
	'"New Hampshire"', 
	'"New Jersey"', 
	'"New Mexico"', 
	'"New York"', 
	'"North Carolina"', 
	'"North Dakota"', 
	'"Ohio"',  
	'"Oklahoma"',  
	'"Oregon"',  
	'"Pennsylvania"',  
	'"Rhode Island"',  
	'"South Carolina"',  
	'"South Dakota"', 
	'"Tennessee"',  
	'"Texas"',  
	'"Utah"',  
	'"Vermont"',  
	'"Virginia"',  
	'"Washington"',  
	'"West Virginia"',  
	'"Wisconsin"',  
	'"Wyoming"'
);